import { KPI, KPIStats } from "@/types";

export const mockKPIs: KPI[] = [
  {
    id: "kpi-1",
    user_id: "u3",
    user_full_name: "Lê Hoàng Nam",
    user_role: "Leader",
    kpi_name: "Số công việc hoàn thành",
    description: "Số lượng công việc (jobs) đóng trong tháng của nhóm",
    kpi_type: "AUTOMATIC",
    related_module: "TASKS",
    target_value: 50,
    unit: "công việc",
    current_value: 42,
    completion_percentage: 84,
    status: "IN_PROGRESS",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u1",
    created_at: "2026-06-01T08:00:00.000Z",
    updated_at: "2026-06-29T10:00:00.000Z"
  },
  {
    id: "kpi-2",
    user_id: "u3",
    user_full_name: "Lê Hoàng Nam",
    user_role: "Leader",
    kpi_name: "Tỷ lệ phản hồi",
    description: "Tỷ lệ phản hồi khách hàng trung bình của nhóm",
    kpi_type: "AUTOMATIC",
    related_module: "FINANCE",
    target_value: 95,
    unit: "%",
    current_value: 93,
    completion_percentage: 97.89,
    status: "IN_PROGRESS",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u1",
    created_at: "2026-06-01T08:00:00.000Z",
    updated_at: "2026-06-29T10:00:00.000Z"
  },
  {
    id: "kpi-3",
    user_id: "u2",
    user_full_name: "Trần Thị Bích",
    user_role: "Worker",
    kpi_name: "Số công việc hoàn thành",
    description: "Số lượng công việc hoàn thành cá nhân",
    kpi_type: "MANUAL",
    target_value: 50,
    unit: "công việc",
    current_value: 54,
    completion_percentage: 108,
    status: "OVERACHIEVED",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u3",
    created_at: "2026-06-01T08:30:00.000Z",
    updated_at: "2026-06-29T09:15:00.000Z"
  },
  {
    id: "kpi-4",
    user_id: "u2",
    user_full_name: "Trần Thị Bích",
    user_role: "Worker",
    kpi_name: "Tỷ lệ phản hồi",
    description: "Tỷ lệ phản hồi khách hàng cá nhân",
    kpi_type: "AUTOMATIC",
    related_module: "TASKS",
    target_value: 95,
    unit: "%",
    current_value: 90,
    completion_percentage: 94.74,
    status: "IN_PROGRESS",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u3",
    created_at: "2026-06-01T08:30:00.000Z",
    updated_at: "2026-06-29T09:15:00.000Z"
  },
  {
    id: "kpi-5",
    user_id: "u4",
    user_full_name: "Phạm Minh Tuấn",
    user_role: "Worker",
    kpi_name: "Số công việc hoàn thành",
    description: "Số lượng công việc hoàn thành cá nhân",
    kpi_type: "MANUAL",
    target_value: 50,
    unit: "công việc",
    current_value: 49,
    completion_percentage: 98,
    status: "IN_PROGRESS",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u3",
    created_at: "2026-06-01T08:45:00.000Z",
    updated_at: "2026-06-29T11:00:00.000Z"
  },
  {
    id: "kpi-6",
    user_id: "u4",
    user_full_name: "Phạm Minh Tuấn",
    user_role: "Worker",
    kpi_name: "Tỷ lệ phản hồi",
    description: "Tỷ lệ phản hồi khách hàng cá nhân",
    kpi_type: "MANUAL",
    target_value: 95,
    unit: "%",
    current_value: 86,
    completion_percentage: 90.53,
    status: "IN_PROGRESS",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u3",
    created_at: "2026-06-01T08:45:00.000Z",
    updated_at: "2026-06-29T11:00:00.000Z"
  },
  {
    id: "kpi-7",
    user_id: "u5",
    user_full_name: "Hoàng Minh Trí",
    user_role: "Worker",
    kpi_name: "Doanh số bán hàng",
    description: "Tổng doanh thu mang về trong tháng",
    kpi_type: "MANUAL",
    target_value: 100000000,
    unit: "VNĐ",
    current_value: 30000000,
    completion_percentage: 30,
    status: "FAILED",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u1",
    created_at: "2026-06-01T08:00:00.000Z",
    updated_at: "2026-06-29T10:00:00.000Z"
  },
  {
    id: "kpi-8",
    user_id: "u6",
    user_full_name: "Ngô Thanh Vân",
    user_role: "Worker",
    kpi_name: "Số khách hàng mới",
    description: "Khách hàng đăng ký mới do cá nhân phụ trách",
    kpi_type: "AUTOMATIC",
    related_module: "CUSTOMERS",
    target_value: 20,
    unit: "khách",
    current_value: 5,
    completion_percentage: 25,
    status: "FAILED",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u1",
    created_at: "2026-06-01T08:00:00.000Z",
    updated_at: "2026-06-29T10:00:00.000Z"
  },
  {
    id: "kpi-9",
    user_id: "u7",
    user_full_name: "Đặng Hữu Phước",
    user_role: "Leader",
    kpi_name: "Thời gian xử lý ticket",
    description: "Thời gian trung bình đóng ticket hỗ trợ",
    kpi_type: "AUTOMATIC",
    related_module: "TASKS",
    target_value: 100,
    unit: "%",
    current_value: 100,
    completion_percentage: 100,
    status: "COMPLETED",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u1",
    created_at: "2026-06-01T08:00:00.000Z",
    updated_at: "2026-06-29T10:00:00.000Z"
  },
  {
    id: "kpi-10",
    user_id: "u8",
    user_full_name: "Vũ Ngọc Ánh",
    user_role: "Worker",
    kpi_name: "Gọi điện CSKH",
    description: "Số cuộc gọi chăm sóc khách hàng hàng tuần",
    kpi_type: "MANUAL",
    target_value: 100,
    unit: "cuộc",
    current_value: 100,
    completion_percentage: 100,
    status: "COMPLETED",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u3",
    created_at: "2026-06-01T08:00:00.000Z",
    updated_at: "2026-06-29T10:00:00.000Z"
  },
  {
    id: "kpi-11",
    user_id: "u5",
    user_full_name: "Hoàng Minh Trí",
    user_role: "Worker",
    kpi_name: "Tỷ lệ chốt sale",
    description: "Tỷ lệ chuyển đổi khách hàng tiềm năng thành đơn",
    kpi_type: "AUTOMATIC",
    related_module: "FINANCE",
    target_value: 30,
    unit: "%",
    current_value: 35,
    completion_percentage: 116.67,
    status: "OVERACHIEVED",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u1",
    created_at: "2026-06-01T08:00:00.000Z",
    updated_at: "2026-06-29T10:00:00.000Z"
  },
  {
    id: "kpi-12",
    user_id: "u6",
    user_full_name: "Ngô Thanh Vân",
    user_role: "Worker",
    kpi_name: "Đánh giá 5 sao",
    description: "Số lượng khách hàng để lại đánh giá tốt",
    kpi_type: "MANUAL",
    target_value: 15,
    unit: "đánh giá",
    current_value: 6,
    completion_percentage: 40,
    status: "FAILED",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u1",
    created_at: "2026-06-01T08:00:00.000Z",
    updated_at: "2026-06-29T10:00:00.000Z"
  },
  {
    id: "kpi-13",
    user_id: "u9",
    user_full_name: "Bùi Tiến Dũng",
    user_role: "Worker",
    kpi_name: "Đạt doanh số tháng",
    description: "Hoàn thành 100% doanh thu được giao",
    kpi_type: "AUTOMATIC",
    related_module: "FINANCE",
    target_value: 50000000,
    unit: "VNĐ",
    current_value: 50000000,
    completion_percentage: 100,
    status: "COMPLETED",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u1",
    created_at: "2026-06-01T08:00:00.000Z",
    updated_at: "2026-06-29T10:00:00.000Z"
  },
  {
    id: "kpi-14",
    user_id: "u10",
    user_full_name: "Lý Nhã Kỳ",
    user_role: "Worker",
    kpi_name: "Báo cáo nội bộ",
    description: "Nộp báo cáo công việc đúng hạn",
    kpi_type: "MANUAL",
    target_value: 4,
    unit: "báo cáo",
    current_value: 3,
    completion_percentage: 75,
    status: "IN_PROGRESS",
    period_type: "MONTHLY",
    period: 6,
    year: 2026,
    created_by: "u3",
    created_at: "2026-06-01T08:00:00.000Z",
    updated_at: "2026-06-29T10:00:00.000Z"
  }
];

export const mockKPIStats: KPIStats = {
  total_kpis: 6,
  completed_kpis: 0,
  in_progress_kpis: 5,
  failed_kpis: 0,
  overachieved_kpis: 1,
  average_completion_rate: 93.87,
  completion_rate_by_status: {
    IN_PROGRESS: 83.33,
    OVERACHIEVED: 16.67,
    COMPLETED: 0,
    FAILED: 0
  }
};
